title: Am I Responsive? (zachharkey)
email: zachharkey@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: /am-i-responsive
url: http://zachharkey.github.io/ # the base hostname & protocol for your site
twitter_username: zachharkey
github_username:  zachharkey

# Build settings
markdown: kramdown
